# This file should contain all the record creation needed to seed the database with its default values.
# data whiout foreign key

User.create(username: "silvia",email: "silvia@gmail.com", password: 'admin')
City.create(city_name: "Mexico")
City.create(city_name: "Canada")
City.create(city_name: "EU")
City.create(city_name: "Spain")
City.create(city_name: "Brazil")
City.create(city_name: "England")

Course.create(name: "React", description: "A React course is a learning program that teaches students how to build web applications using the React JavaScript library. React is a popular front-end framework that allows developers to build complex user interfaces using a modular, component-based approach. A typical React course covers topics such as setting up a development environment, creating and managing components, handling data and state, routing, and working with APIs. React courses may also cover related technologies such as Redux for managing state, and React Native for building mobile applications. Students may learn through a combination of lectures, tutorials, and hands-on projects, and may have the opportunity to build their own portfolio of React projects to showcase their skills to potential employers.", max_num_students: 20,picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/React.svg/800px-React.svg.png",user_id: User.first.id)
Course.create(name: "Redux", description: "Redux is a state management library for JavaScript applications that helps manage complex application state in a predictable way. It provides a centralized store that holds the entire state of the application, and actions that describe the changes to that state. These actions are dispatched to the store, which in turn triggers the reducers, pure functions that update the state in response to the actions. The updated state is then propagated to the components of the application via the store, allowing for a clear unidirectional flow of data. In a Redux course, students typically learn the principles of Redux, its core concepts, and how to implement it in a real-world JavaScript application. They may also learn about related libraries and tools such as React, React Native, and Redux Toolkit.", max_num_students: 20,picture: "https://digital55.com/wp-content/uploads/2022/01/Cuando_y_por_que_debo_usar_redux_en_mis_proyectos_frontend.jpg",user_id: User.first.id)
Course.create(name: "Ruby", description: "A Ruby course typically teaches the Ruby programming language, which is a high-level, object-oriented language known for its simplicity and productivity. The course would likely cover the basics of the language, such as syntax, data types, and control structures, as well as more advanced topics like object-oriented programming, modules, and metaprogramming. Students would learn how to write and test Ruby code, use Ruby libraries and frameworks, and build web applications using Ruby on Rails. The course may also cover best practices for software development, such as version control and testing methodologies.", max_num_students: 20,picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/1200px-Ruby_logo.svg.png",user_id: User.first.id)
Course.create(name: "Rails", description: "A Rails course typically covers the fundamentals of Ruby on Rails, a popular web application framework. It usually starts with an introduction to Ruby, the programming language that powers Rails, and covers topics such as MVC architecture, routing, database integration, and testing. Students may also learn about advanced features of Rails, such as caching, security, and deployment to production environments. By the end of the course, students should have a strong understanding of how to build a functional web application using Rails. Some courses may also include practical projects or assignments to help students apply what they've learned in a real-world context.", max_num_students: 20,picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ruby_On_Rails_Logo.svg/1200px-Ruby_On_Rails_Logo.svg.png",user_id: User.first.id)
Course.create(name: "HTML5", description: "An HTML (Hypertext Markup Language) course is designed to teach you the fundamentals of web development using HTML, which is the backbone of every website. The course typically covers topics such as HTML syntax, text formatting, links, images, tables, forms, and basic CSS (Cascading Style Sheets) concepts. You will learn how to structure a web page using HTML tags, create headings, paragraphs, and lists, add images and links, and create basic forms. By the end of the course, you will have a solid foundation in HTML and be able to create and publish a basic website.", max_num_students: 20,picture: "https://www.alura.com.br/artigos/assets/html-css-js/imagem-1.png",user_id: User.first.id)
Course.create(name: "Bootstrap", description: "A bootstrap course, also known as a bootcamp, is an intensive and immersive training program that provides hands-on education and practical experience in a particular field or technology. These courses typically aim to quickly teach practical skills that can be applied to real-world situations, often with a focus on job readiness. Bootcamps are usually shorter than traditional education programs, ranging from a few weeks to several months, and often involve a mix of classroom instruction, projects, and mentorship. Some common examples of bootstrap courses include coding bootcamps, data science bootcamps, and cybersecurity bootcamps.", max_num_students: 20,picture:"https://getbootstrap.com/docs/5.3/assets/img/bootstrap-icons.png",user_id: User.first.id)
